# Generated by Django 5.2.1 on 2025-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
