# Generated by Django 5.2.1 on 2025-05-25 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_emailconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='user',
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
